### ISSUE TITLE
singly Linked List

### ISSUE THREAD

**Issue by 17vijay2002** [soniyash9000/Data-Structure-and-Algotihms#26]

**Comment by Shivam7679** [comment]
Hi! can you assign me this issue?

**Comment by soniyash9000** [comment]
I have assigned you the issue.

**Comment by Akshat-Bhatnagar** [comment]
I want to work on this issue . Please assign me this issue @soniyash9000

**Comment by yashSoni9000** [comment]
I have assigned you the isue @Akshat-Bhatnagar

**Comment by soniyash9000** [comment]
Done
